package lt.saltyjuice.dragas.chatty.v3.core.mock

import lt.saltyjuice.dragas.chatty.v3.core.adapter.Adapter

class MockAdapter private constructor() : Adapter<String, MockRequest, MockResponse, String>()
{
    /**
     * Deserializes response from server to something more usable in application.
     * @param block a string block which is received from server
     * @return a deserialized [Request] object
     */
    override fun deserialize(block: String): MockRequest
    {
        val split = block.split(":")
        return MockRequest(split[0], split[1])
    }

    /**
     * Serializes response to server from something that was used in application.
     * @param any a response object that's been generated by implementing application
     * @return [String] representation of that particular [Response] object
     */
    override fun serialize(any: MockResponse): String
    {
        return "${any.fieldName}:${any.fieldValue}"
    }

    companion object
    {
        @JvmStatic
        val instance: MockAdapter by lazy()
        {
            MockAdapter()
        }
    }
}