package lt.saltyjuice.dragas.chatty.v3.core.adapter


/**
 * An interface noting that implementing class can serialize responses to server.
 *
 * Since there are many formats in how you can transfer data, the implementation is left for
 * particular application.
 */
interface Serializer<in Response, Block>
{
    /**
     * Serializes response to server from something that was used in application.
     * @param any a response object that's been generated by implementing application
     * @return [String] representation of that particular [Response] object
     */
    fun serialize(any: Response): Block
}