package lt.saltyjuice.dragas.chatty.v3.core.route

import lt.saltyjuice.dragas.chatty.v3.core.main.Utility

/**
 * Base class for all controllers.
 *
 * Design wise, all helpers methods for formatting responses should be provided here.
 */
abstract class Controller<Response>
{
    private val mResponses: ArrayList<Response> = ArrayList()
    /**
     * Saves the response so that it would be later consumed and sent.
     */
    protected open fun writeResponse(response: Response)
    {
        mResponses.add(response)
    }

    /**
     * Gets all responses generated by this controller and cleans the internal buffer.
     */
    fun getResponses(): List<Response>
    {
        return Utility.copyAndClean(mResponses)
    }
}